"use server";
import { redirect } from "next/navigation";
import { requireAuthenticatedUser, requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { canCreateDocuments, canManageDocument, documentVisibilityWhere } from "./authorization";
import { addVersion, createDocument, relationFields, type RelationField } from "./service";
const value=(f:FormData,k:string)=>String(f.get(k)||"").trim();
const fail=(path:string,e:unknown):never=>redirect(`${path}${path.includes("?")?"&":"?"}error=${encodeURIComponent(e instanceof Error?e.message:"Operation failed.")}`);

export async function uploadDocument(f:FormData){const user=await requireAuthenticatedUser(),returnTo=value(f,"returnTo")||"/documents";if(!canCreateDocuments(user))fail(returnTo,"You are not authorized to upload documents.");const relationField=value(f,"relationType") as RelationField;if(!relationFields.includes(relationField))fail(returnTo,"Invalid related record type.");const file=f.get("file");if(!(file instanceof File)||!value(f,"title"))fail(returnTo,"A title and file are required.");try{const d=await createDocument({title:value(f,"title"),description:value(f,"description"),categoryId:value(f,"categoryId"),sensitivity:user.role==="ADMIN"&&value(f,"sensitivity")==="RESTRICTED"?"RESTRICTED":"NORMAL",relationField,relationId:value(f,"relationId"),file:file as File},user);redirect(`/documents/${d.id}?success=Document uploaded.`);}catch(e){fail(returnTo,e)}}
export async function uploadDocumentVersion(f:FormData){const user=await requireAuthenticatedUser(),id=value(f,"documentId"),file=f.get("file");const d=await prisma.document.findFirst({where:{id,...documentVisibilityWhere(user)}});if(!d||!canManageDocument(user,d))fail(`/documents/${id}`,"You are not authorized to replace this file.");if(!(file instanceof File))fail(`/documents/${id}`,"Choose a file.");try{await addVersion(id,file as File,value(f,"notes"),user);}catch(e){fail(`/documents/${id}`,e)}redirect(`/documents/${id}?success=New version uploaded.`)}
export async function updateDocument(f:FormData){const user=await requireAuthenticatedUser(),id=value(f,"documentId"),d=await prisma.document.findFirst({where:{id,...documentVisibilityWhere(user)}});if(!d||!canManageDocument(user,d))fail(`/documents/${id}`,"Not authorized.");const categoryId=value(f,"categoryId")||null;if(categoryId&&!await prisma.documentCategory.findFirst({where:{id:categoryId,organizationId:user.organizationId}}))fail(`/documents/${id}`,"Invalid category.");await prisma.$transaction([prisma.document.update({where:{id},data:{title:value(f,"title"),description:value(f,"description")||null,categoryId}}),prisma.documentActivity.create({data:{organizationId:user.organizationId,documentId:id,userId:user.id,type:"METADATA_CHANGED"}})]);redirect(`/documents/${id}?success=Metadata updated.`)}
export async function toggleDocumentArchive(f:FormData){const user=await requireAuthenticatedUser(),id=value(f,"documentId"),d=await prisma.document.findFirst({where:{id,...documentVisibilityWhere(user)}});if(!d||!canManageDocument(user,d))fail(`/documents/${id}`,"Not authorized.");const archived=d!.status!=="ARCHIVED";await prisma.$transaction([prisma.document.update({where:{id},data:{status:archived?"ARCHIVED":"ACTIVE",archivedAt:archived?new Date():null}}),prisma.documentActivity.create({data:{organizationId:user.organizationId,documentId:id,userId:user.id,type:archived?"ARCHIVED":"RESTORED"}})]);redirect(`/documents/${id}?success=Document ${archived?"archived":"restored"}.`)}
export async function saveCategory(f:FormData){const user=await requireRole("ADMIN"),id=value(f,"id"),name=value(f,"name");if(!name)fail("/administration/documents","Category name is required.");try{if(id)await prisma.documentCategory.updateMany({where:{id,organizationId:user.organizationId},data:{name,description:value(f,"description")||null,active:value(f,"active")==="true"}});else await prisma.documentCategory.create({data:{organizationId:user.organizationId,name,description:value(f,"description")||null}});}catch{fail("/administration/documents","Category names must be unique.")}redirect("/administration/documents?success=Category saved.")}
