import { prisma } from "@/lib/prisma"; import { requirePortalUser } from "@/lib/portal/session"; import { isPublishableInvoice,portalScope } from "@/lib/portal/security";
const invoiceStatuses=["ISSUED","SENT","PARTIALLY_PAID","PAID","OVERDUE"] as const;
export async function portalDashboard(){const user=await requirePortalUser(),scope=portalScope(user);const [client,projects,documents,invoices,rentals,approvals,signatures]=await Promise.all([
 prisma.client.findFirstOrThrow({where:{id:user.clientId,organizationId:user.organizationId},select:{name:true,displayName:true}}),
 prisma.project.findMany({where:{...scope,portalVisible:true,status:{notIn:["CANCELLED","ARCHIVED"]}},select:{id:true,name:true,projectNumber:true,status:true,targetEndDate:true,clientDescription:true},orderBy:{updatedAt:"desc"},take:6}),
 prisma.documentPortalShare.findMany({where:{...scope,withdrawnAt:null,document:{status:"ACTIVE",currentVersionId:{not:null}}},select:{document:{select:{id:true,title:true,updatedAt:true,category:{select:{name:true}}}}},orderBy:{sharedAt:"desc"},take:6}),
 prisma.invoice.findMany({where:{...scope,portalPublished:true,status:{in:[...invoiceStatuses]}},select:{id:true,invoiceNumber:true,status:true,dueDate:true,total:true,amountPaid:true,balanceDue:true,currency:true},orderBy:{issueDate:"desc"},take:8}),
 prisma.rental.findMany({where:{...scope,portalVisible:true,status:{notIn:["DRAFT","CANCELLED"]}},select:{id:true,rentalNumber:true,status:true,reservationStart:true,reservationEnd:true,project:{select:{name:true,portalVisible:true}},items:{select:{equipment:{select:{name:true,assetNumber:true}}}}},orderBy:{reservationStart:"desc"},take:8}),
 prisma.clientApprovalRequest.findMany({where:{...scope},include:{project:{select:{id:true,name:true,portalVisible:true}},document:{select:{id:true,title:true,portalShares:{where:{clientId:user.clientId,withdrawnAt:null},select:{id:true}}}}},orderBy:{requestedAt:"desc"}}),
 prisma.signatureRequest.findMany({where:{organizationId:user.organizationId,status:{notIn:["DRAFT","CANCELLED"]},signers:{some:{clientContact:{clientId:user.clientId},...(user.clientContactId?{clientContactId:user.clientContactId}:{})}}},select:{id:true,title:true,status:true,expiresAt:true,completedAt:true},orderBy:{createdAt:"desc"}})
]);return{user,client,projects,documents:documents.map(x=>x.document),invoices:invoices.filter(x=>isPublishableInvoice(x.status)),rentals,approvals,signatures}}
export async function portalProject(id:string){const u=await requirePortalUser();return prisma.project.findFirst({where:{id,...portalScope(u),portalVisible:true},select:{id:true,name:true,projectNumber:true,status:true,startDate:true,targetEndDate:true,clientDescription:true,milestones:{where:{portalVisible:true},select:{id:true,name:true,status:true,targetDate:true,completedAt:true,clientDescription:true},orderBy:{sortOrder:"asc"}}}})}
export async function portalDocument(id:string){const u=await requirePortalUser();return prisma.document.findFirst({where:{id,organizationId:u.organizationId,status:"ACTIVE",portalShares:{some:{clientId:u.clientId,withdrawnAt:null}}},select:{id:true,title:true,updatedAt:true,category:{select:{name:true}},currentVersion:{select:{id:true,originalFilename:true,mimeType:true,sizeBytes:true,uploadedAt:true}}}})}
