import { DocumentSection } from "@/components/document-section";
import Link from "next/link";
import { userLabel } from "@/modules/tasks/user-label";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { Notice, StatusBadge, SubmitButton, inputClass } from "@/components/ui";
import { formatDate } from "@/lib/format";
import { addChecklistItem, addTaskComment, toggleChecklistItem, updateTask } from "@/modules/tasks/actions";
import { isDueSoon, isOverdue } from "@/modules/tasks/constants";
import { getTaskDetail, getTaskOptions } from "@/modules/tasks/data";
import { TaskForm } from "@/modules/tasks/task-form";

export const dynamic = "force-dynamic";
export default async function TaskDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { id } = await params; const query = await searchParams; const [task, options] = await Promise.all([getTaskDetail(id), getTaskOptions()]); if (!task) notFound();
  return <><PageHeader actions={<Link className="rounded-sm border border-[color:var(--border)] px-4 py-2 text-sm font-semibold" href={`/tasks/new?parentId=${task.id}&projectId=${task.projectId ?? ""}`}>Add subtask</Link>} description={`${task.project?.name ?? "Standalone task"}${task.milestone ? ` · ${task.milestone.name}` : ""}`} title={task.title} />
    <Notice message={query.error} tone="error" /><Notice message={query.success} tone="success" />
    {(isOverdue(task) || isDueSoon(task)) && <div className={`mb-4 rounded-sm border p-3 text-sm font-semibold ${isOverdue(task) ? "text-[color:var(--danger)]" : "text-[color:var(--accent)]"}`}>{isOverdue(task) ? `Overdue since ${formatDate(task.dueDate)}` : `Due soon: ${formatDate(task.dueDate)}`}</div>}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]"><div className="space-y-6">
      <section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><h2 className="mb-4 font-semibold">Task details</h2><TaskForm action={updateTask} options={options} submitLabel="Save changes" task={task} /></section>
      <section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Subtasks</h2><p className="text-xs text-[color:var(--muted)]">Separate work with its own owner and due date.</p></div><span className="text-sm">{task.subtasks.filter((x) => x.status === "COMPLETED").length}/{task.subtasks.length} complete</span></div><div className="space-y-2">{task.subtasks.map((subtask) => <Link className="flex items-center justify-between rounded-sm border border-[color:var(--border)] p-3" href={`/tasks/${subtask.id}`} key={subtask.id}><span>{subtask.title}</span><StatusBadge status={subtask.status} /></Link>)}{!task.subtasks.length && <p className="text-sm text-[color:var(--muted)]">No subtasks yet.</p>}</div></section>
      <section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><h2 className="font-semibold">Checklist</h2><p className="mb-3 text-xs text-[color:var(--muted)]">Quick steps that do not need their own assignee or dates.</p><div className="space-y-2">{task.checklistItems.map((item) => <form action={toggleChecklistItem} key={item.id}><input name="taskId" type="hidden" value={task.id} /><input name="id" type="hidden" value={item.id} /><button className={`w-full rounded-sm border border-[color:var(--border)] p-3 text-left text-sm ${item.completed ? "line-through opacity-60" : ""}`}>{item.completed ? "✓" : "○"} {item.text}</button></form>)}</div><form action={addChecklistItem} className="mt-3 flex gap-2"><input name="taskId" type="hidden" value={task.id} /><input className={inputClass} maxLength={300} name="text" placeholder="Add a checklist item" required /><SubmitButton>Add</SubmitButton></form></section>
      <section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><h2 className="mb-3 font-semibold">Comments</h2><form action={addTaskComment}><input name="taskId" type="hidden" value={task.id} /><textarea className={`${inputClass} min-h-20`} maxLength={5000} name="content" placeholder="Add a plain-text comment" required /><div className="mt-2"><SubmitButton>Comment</SubmitButton></div></form><div className="mt-5 space-y-4">{task.comments.map((comment) => <article className="border-t border-[color:var(--border)] pt-3" key={comment.id}><div className="flex justify-between text-xs text-[color:var(--muted)]"><strong>{userLabel(comment.user)}</strong><time>{comment.createdAt.toLocaleString()}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{comment.content}</p></article>)}</div></section>
    </div><aside className="space-y-4"><section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><h2 className="font-semibold">At a glance</h2><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-[color:var(--muted)]">Created by</dt><dd>{userLabel(task.createdBy)}</dd></div><div><dt className="text-[color:var(--muted)]">Started</dt><dd>{formatDate(task.startDate)}</dd></div><div><dt className="text-[color:var(--muted)]">Completed</dt><dd>{formatDate(task.completedAt)}</dd></div></dl></section><section className="rounded-sm border border-[color:var(--border)] bg-[color:var(--panel)] p-5"><h2 className="font-semibold">Activity</h2><div className="mt-3 space-y-3">{task.activities.map((activity) => <div className="border-l-2 border-[color:var(--border)] pl-3 text-sm" key={activity.id}><p><strong>{userLabel(activity.user)}</strong> · {activity.type.replaceAll("_", " ").toLowerCase()}</p>{activity.detail && <p className="text-[color:var(--muted)]">{activity.detail}</p>}<time className="text-xs text-[color:var(--muted)]">{activity.createdAt.toLocaleString()}</time></div>)}</div></section></aside></div>
  <div className="mt-5"><DocumentSection relationType="taskId" relationId={task.id} returnTo={`/tasks/${task.id}`}/></div></>;
}
