"use server";
import { redirect } from "next/navigation";
import { requireAuthenticatedUser } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { requireAdmin, requireCreateProject, requireProjectManagement } from "./authorization";
import { memberSchema, message, milestoneSchema, noteSchema, projectSchema, roleSchema, val } from "./validation";
const fail = (path: string, text: string): never => redirect(`${path}${path.includes("?") ? "&" : "?"}error=${encodeURIComponent(text)}`);
const projectInput = (f: FormData) => ({ name: val(f,"name"), projectNumber: val(f,"projectNumber"), description: val(f,"description"), status: val(f,"status"), priority: val(f,"priority"), projectManagerId: val(f,"projectManagerId"), startDate: val(f,"startDate"), targetEndDate: val(f,"targetEndDate"), actualEndDate: val(f,"actualEndDate"), clientId: val(f,"clientId"), clientName: val(f,"clientName"), location: val(f,"location"), notes: val(f,"notes") });
async function editable(id: string) { const user = await requireAuthenticatedUser(); const p = await prisma.project.findFirst({ where: { id, organizationId: user.organizationId } }); if (!p) fail("/projects", "Project not found."); await requireProjectManagement(p!); return { o: { id: user.organizationId }, p: p!, user }; }
async function validEmployee(id: string | undefined, organizationId: string) { if (!id) return; if (!await prisma.employee.findFirst({ where: { id, organizationId }, select: { id: true } })) throw new Error("The selected employee does not belong to this organization."); }
async function validClient(id: string | undefined, organizationId: string) { if (!id) return; if (!await prisma.client.findFirst({ where: { id, organizationId }, select: { id: true } })) throw new Error("The selected client does not belong to this organization."); }
export async function createProject(f: FormData) { const user = await requireCreateProject(); const parsed = projectSchema.safeParse(projectInput(f)); if (!parsed.success) fail("/projects/new", message(parsed.error)); const o = { id: user.organizationId }; if (user.role === "MANAGER" && (!user.employeeId || parsed.data!.projectManagerId !== user.employeeId)) fail("/projects/new", "Managers must be the project manager of projects they create."); let id = ""; try { await validEmployee(parsed.data!.projectManagerId, o.id); await validClient(parsed.data!.clientId, o.id); const project = await prisma.project.create({ data: { ...parsed.data!, organizationId: o.id, activities: { create: { organizationId: o.id, type: "SYSTEM", content: "Project created." } } } }); id = project.id; } catch (e) { if ((e as Error).message.includes("organization")) fail("/projects/new", (e as Error).message); fail("/projects/new", "Project could not be created. Check the project number is unique."); } redirect(`/projects/${id}?success=Project created.`); }
export async function updateProject(f: FormData) { const id=val(f,"id"), parsed=projectSchema.safeParse(projectInput(f)); if (!parsed.success) fail(`/projects/${id}/edit`, message(parsed.error)); const {o,p,user}=await editable(id); if (user.role !== "ADMIN" && parsed.data!.projectManagerId !== (p.projectManagerId ?? undefined)) fail(`/projects/${id}/edit`,"Only administrators can change the project manager."); try { await validEmployee(parsed.data!.projectManagerId,o.id); await validClient(parsed.data!.clientId,o.id); await prisma.$transaction([prisma.project.update({where:{id},data:parsed.data!}), ...(p.status !== parsed.data!.status ? [prisma.projectActivity.create({data:{organizationId:o.id,projectId:id,type:"SYSTEM",content:`Status changed from ${p.status} to ${parsed.data!.status}.`}})] : [])]); } catch { fail(`/projects/${id}/edit`,"Project could not be updated. Check its number and relationships."); } redirect(`/projects/${id}?success=Project updated.`); }
export async function addMember(f: FormData) { const projectId=val(f,"projectId"), parsed=memberSchema.safeParse({employeeId:val(f,"employeeId"),projectRoleId:val(f,"projectRoleId"),joinedAt:val(f,"joinedAt"),notes:val(f,"notes")}); if(!parsed.success) fail(`/projects/${projectId}?tab=team`,message(parsed.error)); const {o}=await editable(projectId); try { await validEmployee(parsed.data!.employeeId,o.id); if(parsed.data!.projectRoleId && !await prisma.projectRole.findFirst({where:{id:parsed.data!.projectRoleId,organizationId:o.id,active:true}})) throw new Error(); await prisma.$transaction([prisma.projectMember.upsert({where:{projectId_employeeId:{projectId,employeeId:parsed.data!.employeeId}},create:{...parsed.data!,organizationId:o.id,projectId},update:{projectRoleId:parsed.data!.projectRoleId,joinedAt:parsed.data!.joinedAt,leftAt:null,notes:parsed.data!.notes}}),prisma.projectActivity.create({data:{organizationId:o.id,projectId,type:"SYSTEM",content:"A team member was added or reactivated."}})]); } catch { fail(`/projects/${projectId}?tab=team`,"Team member could not be added. Check the employee and role."); } redirect(`/projects/${projectId}?tab=team&success=Team updated.`); }
export async function updateMember(f: FormData) { const projectId=val(f,"projectId"),id=val(f,"id"),role=val(f,"projectRoleId")||null,notes=val(f,"notes")||null; const {o}=await editable(projectId); if(role&&!await prisma.projectRole.findFirst({where:{id:role,organizationId:o.id}})) fail(`/projects/${projectId}?tab=team`,"Invalid role."); await prisma.projectMember.updateMany({where:{id,projectId,organizationId:o.id},data:{projectRoleId:role,notes}}); redirect(`/projects/${projectId}?tab=team&success=Membership updated.`); }
export async function endMember(f: FormData) { const projectId=val(f,"projectId"),id=val(f,"id"); const {o}=await editable(projectId); await prisma.projectMember.updateMany({where:{id,projectId,organizationId:o.id},data:{leftAt:new Date()}}); redirect(`/projects/${projectId}?tab=team&success=Membership ended.`); }
export async function saveMilestone(f: FormData) { const projectId=val(f,"projectId"),id=val(f,"id"), parsed=milestoneSchema.safeParse({name:val(f,"name"),description:val(f,"description"),targetDate:val(f,"targetDate"),status:val(f,"status"),sortOrder:val(f,"sortOrder")}); if(!parsed.success) fail(`/projects/${projectId}?tab=milestones`,message(parsed.error)); const {o}=await editable(projectId), completedAt=parsed.data!.status==="COMPLETED"?new Date():null; if(id) await prisma.projectMilestone.updateMany({where:{id,projectId,organizationId:o.id},data:{...parsed.data!,completedAt}}); else await prisma.projectMilestone.create({data:{...parsed.data!,completedAt,projectId,organizationId:o.id}}); redirect(`/projects/${projectId}?tab=milestones&success=Milestone saved.`); }
export async function addNote(f: FormData) { const projectId=val(f,"projectId"), parsed=noteSchema.safeParse({content:val(f,"content")}); if(!parsed.success) fail(`/projects/${projectId}?tab=activity`,message(parsed.error)); const {o}=await editable(projectId); await prisma.projectActivity.create({data:{organizationId:o.id,projectId,content:parsed.data!.content,type:"NOTE"}}); redirect(`/projects/${projectId}?tab=activity&success=Note added.`); }
export async function createProjectRole(f: FormData) { const user = await requireAdmin(); const p=roleSchema.safeParse({name:val(f,"name"),description:val(f,"description")}); if(!p.success) fail("/administration/project-roles",message(p.error)); const o={id:user.organizationId}; try{await prisma.projectRole.create({data:{...p.data!,organizationId:o.id}})}catch{fail("/administration/project-roles","Role name must be unique.")} redirect("/administration/project-roles?success=Project role created."); }
export async function updateProjectRole(f: FormData) { const user = await requireAdmin(); const id=val(f,"id"),o={id:user.organizationId}; await prisma.projectRole.updateMany({where:{id,organizationId:o.id},data:{active:val(f,"active")==="true"}}); redirect("/administration/project-roles?success=Project role updated."); }
