import type { ProjectStatus } from "@/generated/prisma/enums";
import { getCurrentOrganization } from "@/lib/organization";
import { prisma } from "@/lib/prisma";
import { getCurrentAccess } from "./authorization";
function visibility() { const a=getCurrentAccess(); return a.role === "ADMIN" ? {} : a.employeeId ? { OR: [{ projectManagerId: a.employeeId }, { members: { some: { employeeId: a.employeeId, leftAt: null } } }] } : { id: "__no_authorized_projects__" }; }
export const projectInclude = { projectManager: { include: { position: true } }, members: { orderBy: { createdAt: "asc" as const }, include: { employee: { include: { position: true } }, projectRole: true } }, milestones: { orderBy: [{ sortOrder: "asc" as const }, { targetDate: "asc" as const }] }, activities: { orderBy: { createdAt: "desc" as const } } };
export async function listProjects(filters: { search?: string; status?: ProjectStatus; managerId?: string; lifecycle?: string; page?: number }) { const organization = await getCurrentOrganization(); const page = Math.max(1, filters.page || 1), take = 25, search = filters.search?.trim(); const where = { organizationId: organization.id, ...visibility(), status: filters.status || (filters.lifecycle === "open" ? { in: ["PLANNING", "ACTIVE", "ON_HOLD"] as ProjectStatus[] } : filters.lifecycle === "closed" ? { in: ["COMPLETED", "CANCELLED", "ARCHIVED"] as ProjectStatus[] } : undefined), projectManagerId: filters.managerId || undefined, ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" as const } }, { projectNumber: { contains: search, mode: "insensitive" as const } }, { clientName: { contains: search, mode: "insensitive" as const } }] } : {}) }; const [items, total] = await Promise.all([prisma.project.findMany({ where, include: { projectManager: true }, orderBy: { updatedAt: "desc" }, skip: (page - 1) * take, take }), prisma.project.count({ where })]); return { items, total, page, pages: Math.max(1, Math.ceil(total / take)) }; }
export async function getProject(id: string) { const o = await getCurrentOrganization(); return prisma.project.findFirst({ where: { id, organizationId: o.id, ...visibility() }, include: projectInclude }); }
export async function getProjectOptions() { const o = await getCurrentOrganization(); const [employees, roles] = await Promise.all([prisma.employee.findMany({ where: { organizationId: o.id, employmentStatus: { in: ["ACTIVE", "LEAVE"] } }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }], include: { position: true } }), prisma.projectRole.findMany({ where: { organizationId: o.id, active: true }, orderBy: { name: "asc" } })]); return { employees, roles }; }
export async function listProjectRoles() { const o = await getCurrentOrganization(); return prisma.projectRole.findMany({ where: { organizationId: o.id }, include: { _count: { select: { members: true } } }, orderBy: [{ active: "desc" }, { name: "asc" }] }); }
export async function getProjectsForEmployee(employeeId: string) { const o = await getCurrentOrganization(); return prisma.projectMember.findMany({ where: { organizationId: o.id, employeeId }, include: { project: true, projectRole: true }, orderBy: { createdAt: "desc" } }); }
export async function getProjectDashboardStats() { const o = await getCurrentOrganization(); const [active, planning, onHold, upcoming] = await Promise.all([prisma.project.count({ where: { organizationId: o.id, status: "ACTIVE" } }), prisma.project.count({ where: { organizationId: o.id, status: "PLANNING" } }), prisma.project.count({ where: { organizationId: o.id, status: "ON_HOLD" } }), prisma.projectMilestone.count({ where: { organizationId: o.id, status: { in: ["PENDING", "IN_PROGRESS"] }, targetDate: { gte: new Date(), lte: new Date(Date.now() + 30 * 86400000) } } })]); return { active, planning, onHold, upcoming }; }
