import { z } from "zod";
const optionalText = z.string().trim().transform(v => v || undefined).optional();
const optionalDate = z.string().trim().transform(v => v ? new Date(`${v}T00:00:00.000Z`) : undefined).refine(v => !v || !Number.isNaN(v.valueOf()), "Enter a valid date.");
export const projectSchema = z.object({ name: z.string().trim().min(1, "Name is required.").max(160), projectNumber: optionalText, description: optionalText, status: z.enum(["PLANNING", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED", "ARCHIVED"]), priority: z.enum(["LOW", "NORMAL", "HIGH", "URGENT"]), projectManagerId: optionalText, startDate: optionalDate, targetEndDate: optionalDate, actualEndDate: optionalDate, clientId: optionalText, clientName: optionalText, location: optionalText, notes: optionalText, clientDescription: optionalText, portalVisible: z.boolean() }).refine(v => !v.startDate || !v.targetEndDate || v.targetEndDate >= v.startDate, { message: "Target end date cannot be before start date." }).refine(v => v.status !== "COMPLETED" || !!v.actualEndDate, { message: "An actual end date is required for completed projects." });
export const roleSchema = z.object({ name: z.string().trim().min(1).max(100), description: optionalText });
export const memberSchema = z.object({ employeeId: z.string().min(1), projectRoleId: optionalText, joinedAt: optionalDate, notes: optionalText });
export const milestoneSchema = z.object({ name: z.string().trim().min(1).max(160), description: optionalText, targetDate: optionalDate, status: z.enum(["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED"]), sortOrder: z.coerce.number().int().min(0).default(0) });
export const noteSchema = z.object({ content: z.string().trim().min(1, "Note cannot be empty.").max(4000) });
export const val = (f: FormData, key: string) => String(f.get(key) || "");
export const message = (error: z.ZodError) => error.issues.map(i => i.message).join(" ");
