import type { EquipmentCondition, EquipmentStatus, Prisma, RentalStatus } from "@/generated/prisma/client";
import { requireAuthenticatedUser } from "@/lib/auth/session"; import { prisma } from "@/lib/prisma"; import { conflictWhere, isOverdue, operationallyAvailable } from "./availability";
export async function equipmentOptions(){const u=await requireAuthenticatedUser();return Promise.all([prisma.equipmentCategory.findMany({where:{organizationId:u.organizationId},orderBy:{name:"asc"}}),prisma.equipmentLocation.findMany({where:{organizationId:u.organizationId},orderBy:{name:"asc"}})]).then(([categories,locations])=>({categories,locations}));}
export async function listEquipment(q:Record<string,string|undefined>){const u=await requireAuthenticatedUser(),search=q.search?.trim();return prisma.equipment.findMany({where:{organizationId:u.organizationId,...(q.categoryId?{categoryId:q.categoryId}:{}),...(q.locationId?{locationId:q.locationId}:{}),...(q.status?{status:q.status as EquipmentStatus}:{}),...(q.condition?{condition:q.condition as EquipmentCondition}:{}),...(q.rentable?{rentable:q.rentable==="true"}:{}),...(q.active?{active:q.active==="true"}:{}),...(search?{OR:[{assetNumber:{contains:search,mode:"insensitive"}},{name:{contains:search,mode:"insensitive"}},{serialNumber:{contains:search,mode:"insensitive"}},{manufacturer:{contains:search,mode:"insensitive"}},{model:{contains:search,mode:"insensitive"}}]}:{})},include:{category:true,location:true},orderBy:{assetNumber:"asc"}})}
export async function getEquipment(id:string){const u=await requireAuthenticatedUser();return prisma.equipment.findFirst({where:{id,organizationId:u.organizationId},include:{category:true,location:true,rentalItems:{include:{rental:{include:{client:true,project:true}}},orderBy:{rental:{reservationStart:"desc"}}}}})}
export async function listRentals(q:Record<string,string|undefined>){const u=await requireAuthenticatedUser(),search=q.search?.trim();return prisma.rental.findMany({where:{organizationId:u.organizationId,...(q.status?{status:q.status as RentalStatus}:{}),...(q.clientId?{clientId:q.clientId}:{}),...(q.projectId?{projectId:q.projectId}:{}),...(q.from?{reservationEnd:{gte:new Date(q.from)}}:{}),...(q.to?{reservationStart:{lte:new Date(q.to)}}:{}),...(search?{OR:[{rentalNumber:{contains:search,mode:"insensitive"}},{client:{name:{contains:search,mode:"insensitive"}}},{project:{name:{contains:search,mode:"insensitive"}}}]}:{})},include:{client:true,project:true,_count:{select:{items:true}}},orderBy:{reservationStart:"desc"}})}
export async function rentalOptions(){const u=await requireAuthenticatedUser();const [clients,projects,employees]=await Promise.all([prisma.client.findMany({where:{organizationId:u.organizationId,status:{not:"ARCHIVED"}},include:{contacts:{where:{active:true}}},orderBy:{name:"asc"}}),prisma.project.findMany({where:{organizationId:u.organizationId,status:{notIn:["ARCHIVED","CANCELLED"]}},orderBy:{name:"asc"}}),prisma.employee.findMany({where:{organizationId:u.organizationId,employmentStatus:"ACTIVE"},orderBy:[{lastName:"asc"},{firstName:"asc"}]})]);return {clients,projects,employees}}
export async function availableEquipment(start:Date,end:Date,excludeRentalId?:string){const u=await requireAuthenticatedUser();const blocked=(await prisma.rentalItem.findMany({where:conflictWhere(u.organizationId,start,end,excludeRentalId),select:{equipmentId:true}})).map(x=>x.equipmentId);return prisma.equipment.findMany({where:{organizationId:u.organizationId,id:{notIn:blocked},active:true,rentable:true,status:{in:["AVAILABLE","RESERVED"]}},include:{category:true,location:true},orderBy:{assetNumber:"asc"}})}
export async function getRental(id:string){const u=await requireAuthenticatedUser();return prisma.rental.findFirst({where:{id,organizationId:u.organizationId},include:{client:true,clientContact:true,project:true,invoices:{orderBy:{issueDate:"desc"}},preparedBy:true,checkedOutBy:true,receivedBy:true,items:{include:{equipment:{include:{category:true,location:true}}},orderBy:{equipment:{assetNumber:"asc"}}},activities:{include:{user:{include:{employee:true}}},orderBy:{createdAt:"desc"}}}})}
export async function getRentalDashboard(){const u=await requireAuthenticatedUser(),now=new Date(),soon=new Date(+now+3*86400000);const [checkedOut,dueSoon,candidates,inspection,maintenance]=await Promise.all([prisma.rental.count({where:{organizationId:u.organizationId,status:{in:["CHECKED_OUT","PARTIALLY_RETURNED"]}}}),prisma.rental.count({where:{organizationId:u.organizationId,status:{in:["CHECKED_OUT","PARTIALLY_RETURNED"]},reservationEnd:{gte:now,lte:soon}}}),prisma.rental.findMany({where:{organizationId:u.organizationId,reservationEnd:{lt:now}},select:{reservationEnd:true,status:true}}),prisma.equipment.count({where:{organizationId:u.organizationId,status:"INSPECTION"}}),prisma.equipment.count({where:{organizationId:u.organizationId,status:"MAINTENANCE"}})]);return {checkedOut,dueSoon,overdue:candidates.filter(x=>isOverdue(x,now)).length,inspection,maintenance}}
export function estimatedSubtotal(items:{rate:Prisma.Decimal|null}[]){return items.reduce((sum,x)=>sum+(x.rate?Number(x.rate):0),0)}
export { operationallyAvailable };
