"use server";
import { redirect } from "next/navigation";
import { requireAuthenticatedUser, requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { canEditClient, clientVisibilityWhere } from "./authorization";
import { activitySchema,clientSchema,contactSchema,fields,val } from "./validation";
const fail=(path:string,msg:string):never=>redirect(`${path}${path.includes("?")?"&":"?"}error=${encodeURIComponent(msg)}`);
async function accessible(id:string){const user=await requireAuthenticatedUser();const client=await prisma.client.findFirst({where:{AND:[{id},clientVisibilityWhere(user)]},include:{projects:{select:{projectManagerId:true}}}});if(!client)fail("/clients","Client not found or unavailable.");return {user,client:client!};}
async function editable(id:string){const x=await accessible(id);if(!canEditClient(x.user,x.client))redirect("/forbidden");return x;}
export async function createClient(f:FormData){const user=await requireRole("ADMIN","MANAGER"), parsed=clientSchema.safeParse(fields(f));if(!parsed.success)fail("/clients/new",parsed.error.issues[0]?.message||"Invalid client.");const data=parsed.data!;let id="";try{const c=await prisma.client.create({data:{...data,organizationId:user.organizationId,createdByUserId:user.id}});id=c.id}catch{fail("/clients/new","Client could not be created. Check that the client number is unique.")}redirect(`/clients/${id}?success=Client created.`)}
export async function updateClient(f:FormData){const id=val(f,"id"), parsed=clientSchema.safeParse(fields(f));if(!parsed.success)fail(`/clients/${id}/edit`,parsed.error.issues[0]?.message||"Invalid client.");const data=parsed.data!;await editable(id);try{await prisma.client.update({where:{id},data})}catch{fail(`/clients/${id}/edit`,"Client could not be updated. Check that the client number is unique.")}redirect(`/clients/${id}?success=Client updated.`)}
export async function saveContact(f:FormData){const clientId=val(f,"clientId"),id=val(f,"id"),p=contactSchema.safeParse({firstName:val(f,"firstName"),lastName:val(f,"lastName"),title:val(f,"title"),email:val(f,"email"),phone:val(f,"phone"),mobilePhone:val(f,"mobilePhone"),preferredContactMethod:val(f,"preferredContactMethod")||undefined,primary:val(f,"primary")==="on",active:val(f,"active")!=="false",notes:val(f,"notes")});if(!p.success)fail(`/clients/${clientId}?tab=contacts`,p.error.issues[0]?.message||"Invalid contact.");const data=p.data!;const {user}=await editable(clientId);await prisma.$transaction(async tx=>{if(data.primary)await tx.clientContact.updateMany({where:{clientId,organizationId:user.organizationId},data:{primary:false}});const c=id?await tx.clientContact.update({where:{id,clientId,organizationId:user.organizationId},data}):await tx.clientContact.create({data:{...data,clientId,organizationId:user.organizationId}});if(data.primary)await tx.client.update({where:{id:clientId},data:{primaryContactId:c.id}});else await tx.client.updateMany({where:{id:clientId,primaryContactId:c.id},data:{primaryContactId:null}})});redirect(`/clients/${clientId}?tab=contacts&success=Contact saved.`)}
export async function toggleContact(f:FormData){const clientId=val(f,"clientId"),id=val(f,"id");const {user}=await editable(clientId);const c=await prisma.clientContact.findFirst({where:{id,clientId,organizationId:user.organizationId}});if(!c)fail(`/clients/${clientId}?tab=contacts`,"Contact not found.");await prisma.$transaction([prisma.clientContact.update({where:{id},data:{active:!c!.active,primary:c!.active?false:c!.primary}}),...(c!.active?[prisma.client.updateMany({where:{id:clientId,primaryContactId:id},data:{primaryContactId:null}})]:[])]);redirect(`/clients/${clientId}?tab=contacts&success=Contact updated.`)}
export async function addActivity(f:FormData){const clientId=val(f,"clientId"),p=activitySchema.safeParse({activityType:val(f,"activityType"),summary:val(f,"summary"),occurredAt:val(f,"occurredAt")||new Date()});if(!p.success)fail(`/clients/${clientId}?tab=activity`,p.error.issues[0]?.message||"Invalid activity.");const data=p.data!;const {user}=await accessible(clientId);await prisma.clientActivity.create({data:{...data,clientId,organizationId:user.organizationId,userId:user.id}});redirect(`/clients/${clientId}?tab=activity&success=Activity added.`)}
export async function findDuplicates(f:FormData){const user=await requireRole("ADMIN","MANAGER"),name=val(f,"name"),email=val(f,"generalEmail"),phone=val(f,"mainPhone");if(!name&&!email&&!phone)redirect("/clients/new");const matches=await prisma.client.findMany({where:{organizationId:user.organizationId,OR:[...(name?[{name:{contains:name,mode:"insensitive" as const}}]:[]),...(email?[{generalEmail:{equals:email,mode:"insensitive" as const}}]:[]),...(phone?[{mainPhone:phone}]:[])]},take:5,select:{name:true}});const suffix=matches.length?`Possible duplicates: ${matches.map(x=>x.name).join(", ")}. You may still create this client.`:"No likely duplicates found.";redirect(`/clients/new?duplicate=${encodeURIComponent(suffix)}&name=${encodeURIComponent(name)}&generalEmail=${encodeURIComponent(email)}&mainPhone=${encodeURIComponent(phone)}`)}
